version: "3.8"
services:
  cocorico:
    image: cocolabs/cocorico:latest
    ports:
      - "80:80"
      - "3306:3306"
      - "9001:9001"
      - "27017:27017"
    volumes:
      - ./../:/cocorico
      - ./../tmp/mysql:/var/lib/mysql
      - ./../tmp/mongo:/data/db
    environment:
      HOST_UID: "${UID}"
    tty: true
    stdin_open: true
    command: /bin/bash
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_USERNAME: cocorico
      ADMINER_PASSWORD: cocorico
    depends_on:
      - cocorico
  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"