services:
    sonata.admin.listing:
        class: Cocorico\CoreBundle\Admin\ListingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts", label: "Posts", showMosaicButton: false }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\Listing
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]
            - [ setIncludeVat, ["%cocorico.include_vat%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]

    sonata.admin.listing_characteristic:
        class: Cocorico\CoreBundle\Admin\ListingCharacteristicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts",  label: "Characteristic" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\ListingCharacteristic
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]

    sonata.admin.listing_characteristic_group:
        class: Cocorico\CoreBundle\Admin\ListingCharacteristicGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts",  label: "Characteristic Group"}
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\ListingCharacteristicGroup
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]

    sonata.admin.listing_characteristic_type:
        class: Cocorico\CoreBundle\Admin\ListingCharacteristicTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts",  label: "Characteristic Type" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\ListingCharacteristicType
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]

    sonata.admin.listing_characteristic_value:
        class: Cocorico\CoreBundle\Admin\ListingCharacteristicValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\ListingCharacteristicValue
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]

    sonata.admin.listing_category:
        class: Cocorico\CoreBundle\Admin\ListingCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts",  label: "Category" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\ListingCategory
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setLocales, ["%cocorico.locales%"]]
            - [ setBundlesEnabled, ["%kernel.bundles%"]]

    sonata.admin.invitations:
        class: Cocorico\CoreBundle\Admin\InvitationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: 'User invitation' }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\UserInvitation
            - ~
        calls:
            - [ setTranslationDomain, [ cocorico_user ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.verified-domain:
        class: Cocorico\CoreBundle\Admin\VerifiedDomainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Member organizations", label: 'Verified domains' }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\VerifiedDomain
            - ~
        calls:
            - [ setTranslationDomain, [ cocorico_user ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.member-organization:
        class: Cocorico\CoreBundle\Admin\MemberOrganizationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Member organizations", label: 'Organizations' }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\MemberOrganization
            - ~
        calls:
            - [ setTranslationDomain, [ cocorico_user ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.country-information:
        class: Cocorico\CoreBundle\Admin\CountryInformationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Member organizations", label: 'Country information' }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\CountryInformation
            - ~
        calls:
            - [ setTranslationDomain, [ cocorico_user ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.listing_validation:
        class: Cocorico\CoreBundle\Admin\ListingValidationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Posts", label: "Posts validation" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\Listing
            - ~
        calls:
            - [ setTranslationDomain, [ SonataAdminBundle ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.announcement:
        class: Cocorico\CoreBundle\Admin\AnnouncementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Announcement", label: "Announcements" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\Announcement
            - ~
        calls:
            - [ setTranslationDomain, [ SonataAdminBundle ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]

    sonata.admin.user_announcement:
        class: Cocorico\CoreBundle\Admin\AnnouncementToUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Announcement", label: "Users announcements" }
        arguments:
            - ~
            - Cocorico\CoreBundle\Entity\AnnouncementToUser
            - ~
        calls:
            - [ setTranslationDomain, [ SonataAdminBundle ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]