services:
    sonata.admin.user_address:
        class: Cocorico\UserBundle\Admin\UserAddressAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Cocorico\UserBundle\Entity\UserAddress
            - ~
        calls:
            - [ setTranslationDomain, [cocorico_user]]
            - [ setLocales, ["%cocorico.locales%"]]

    sonata.admin.activation:
        class: Cocorico\UserBundle\Admin\ActivationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true , group: "Users", label: "Pending activations" }
        arguments:
            - ~
            - Cocorico\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [ cocorico_user ] ]
            - [ setLocales, [ "%cocorico.locales%" ] ]