services:
    cocorico_user.authentication_subscriber:
        class: Cocorico\UserBundle\Event\UserAuthenticationSubscriber
        arguments:
            - "@session"
            - "%cocorico.time_zone%"
        tags:
            - { name: kernel.event_subscriber }

    cocorico_user.expiry_subscriber:
        class: Cocorico\UserBundle\Event\UserExpirySubscriber
        arguments:
            - "@router"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_subscriber }

    cocorico_user.on_login_subscriber:
        class: Cocorico\UserBundle\Event\OnLoginSubscriber
        arguments:
        tags:
            - { name: kernel.event_subscriber }