name: deploy

on: [workflow_dispatch]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          SSH_HOST: ${{ secrets.TARGET_HOST }}
          SSH_USER: ${{ secrets.TARGET_USER }}
        run: |
          eval $(ssh-agent -s)
          bash -c 'ssh-add <(echo "$DEPLOYER_PRIVATE_KEY")'
          END

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy
